# Generated by Django 4.2.7 on 2023-11-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='seller_contact',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='seller_name',
        ),
    ]
